/* eslint-disable */
// AUTO-GENERATED by scripts/generate-csvs.mjs — DO NOT EDIT BY HAND.

export type CsvPreset = {
  id: string
  label: string
  filename: string
  contents: string
}

export const BUILTIN_CSVS: CsvPreset[] = [
  {
    id: "alerts",
    label: "Alerts",
    filename: "alerts.csv",
    contents: `Priority [status|c],Name,Status ,Case [boolean|c],SLO,Disposition,AI Disposition,Comments [r],Assignee,Created Date,Tags [chip],Customer Code,Customer Flags [chip]
Medium,Brute Force Attempt on Admin Account,Closed,FALSE,1 minutes,Benign,Unknown,10,Jack Wilson,07/20/2025 04:26:23 AM,"Cloud Misconfig, Exfiltration",ARAR-8474,Repeat Offender
Low,Suspicious Access from Foreign IP,Open,TRUE,5 minutes,Malicious,Suspicious,1,Frank Thompson,07/01/2025 10:45:23 AM,,ARAR-9098,Under Investigation
High,Unusual Script Execution in PowerShell,Open,FALSE,8 hours,Malicious,Suspicious,8,Alice Johnson,07/13/2025 11:01:23 AM,"Phishing, Reconnaissance",ARAR-9610,Under Investigation
Critical,Multiple Failed Login Attempts Detected,Investigating,FALSE,1 hours,Benign,Suspicious,8,Diana Patel,07/15/2025 04:39:23 AM,Phishing,ARAR-3895,
Critical,Unauthorized Access to Confidential Share,Investigating,FALSE,9 minutes,Benign,Unknown,0,Isla Brown,07/31/2025 03:58:23 AM,"Phishing, Reconnaissance",ARAR-9447,"Production System, VIP Account, SOC Watchlist"
Critical,Unexpected Outbound Traffic to Known Malicious IP,Closed,TRUE,8 minutes,Suspicious,Benign,1,Grace Lee,07/04/2025 03:47:23 AM,"Reconnaissance, Endpoint Compromise, Phishing",ARAR-6968,Under Investigation
Low,Elevated Privilege Usage Outside Business Hours,Open,TRUE,10 minutes,Suspicious,Malicious,4,Diana Patel,07/01/2025 09:23:23 AM,"Reconnaissance, Endpoint Compromise",ARAR-6470,
Low,Data Transfer to External Storage,Investigating,TRUE,10 minutes,Benign,Suspicious,3,Hector Garcia,07/15/2025 10:28:23 PM,,ARAR-5647,"VIP Account, Under Investigation"
Low,New Domain Joined to AD from Unrecognized Host,Investigating,FALSE,7 hours,Malicious,Unknown,3,Bob Smith,07/18/2025 04:21:23 AM,Phishing,ARAR-7771,
Low,Unusual Login Pattern Across Multiple Locations,Open,TRUE,10 days,Suspicious,Malicious,7,Frank Thompson,07/30/2025 04:38:23 AM,Exfiltration,ARAR-1295,
High,Anomalous File Download Activity,Investigating,FALSE,7 hours,Suspicious,Unknown,9,Bob Smith,07/16/2025 09:09:23 AM,"Cloud Misconfig, Phishing, Endpoint Compromise",ARAR-2533,
High,Unencrypted Traffic on Sensitive Port,Open,FALSE,1 hours,Benign,Unknown,3,Bob Smith,07/11/2025 03:57:23 AM,"Reconnaissance, Cloud Misconfig",ARAR-7149,"Production System, Repeat Offender, VIP Account"
Low,Misconfigured IAM Role with Excessive Permissions,Investigating,TRUE,8 hours,Benign,Suspicious,7,Hector Garcia,07/28/2025 01:59:23 PM,,ARAR-2395,"Under Investigation, VIP Account"
Medium,S3 Bucket Publicly Accessible,Open,TRUE,5 days,Malicious,Unknown,9,Hector Garcia,07/11/2025 08:00:23 AM,"Exfiltration, Suspicious Behavior",ARAR-4137,"Customer Escalation, SOC Watchlist, Production System"
Medium,Open RDP Port Detected,Investigating,FALSE,8 days,Benign,Suspicious,9,Diana Patel,07/06/2025 03:31:23 AM,"Credential Access, Exfiltration, Brute Force",ARAR-3027,VIP Account
High,Excessive API Calls by Service Account,Closed,TRUE,8 days,Benign,Suspicious,1,Alice Johnson,07/18/2025 09:58:23 PM,"Exfiltration, Phishing, Credential Access",ARAR-7782,VIP Account
Critical,New Device Registered by End User,Open,FALSE,10 hours,Suspicious,Benign,4,Eve Chen,07/28/2025 12:41:23 AM,,ARAR-3354,"Customer Escalation, Repeat Offender, Production System"
Critical,AV Signature Alert from CrowdStrike,Investigating,TRUE,3 minutes,Unknown,Suspicious,5,Grace Lee,07/16/2025 12:23:23 PM,"Exfiltration, Credential Access",ARAR-4163,"Customer Escalation, SOC Watchlist, Under Investigation"
Low,Endpoint Malware Behavior Detected,Investigating,TRUE,8 days,Malicious,Benign,7,Charlie Nguyen,07/12/2025 03:38:23 PM,Credential Access,ARAR-5123,
High,Suspicious Process Chain Observed,Closed,TRUE,5 minutes,Benign,Malicious,2,Jack Wilson,07/08/2025 02:44:23 PM,"Reconnaissance, Cloud Misconfig",ARAR-6350,
Low,DNS Tunneling Behavior Identified,Closed,TRUE,1 minutes,Benign,Suspicious,0,Diana Patel,07/13/2025 10:22:23 PM,"Credential Access, Brute Force",ARAR-6087,"Under Investigation, VIP Account"
Medium,C2 Communication Pattern Found,Investigating,TRUE,9 hours,Benign,Malicious,1,Eve Chen,07/11/2025 07:00:23 AM,Cloud Misconfig,ARAR-9228,
Low,Web Shell Upload Attempt,Open,TRUE,5 minutes,Malicious,Benign,10,Diana Patel,07/28/2025 11:08:23 AM,,ARAR-8833,"Repeat Offender, Customer Escalation"
Low,Exploit Kit Payload Blocked by EDR,Investigating,FALSE,1 days,Malicious,Unknown,5,Jack Wilson,07/25/2025 05:32:23 PM,Credential Access,ARAR-2264,"Production System, Under Investigation"
Critical,Abnormal Cloud Resource Creation Pattern,Closed,TRUE,2 hours,Malicious,Benign,7,Isla Brown,07/03/2025 07:37:23 AM,,ARAR-4426,`
  },
  {
    id: "vulnerability findings",
    label: "Vulnerability Findings",
    filename: "vulnerability findings.csv",
    contents: `CVE,Title,Risk [c],CVSS [c],CISA KEV [boolean|c],EPSS,Affected Assets [r],Findings [r],First Detected,Last Detected
CVE-2024-62436,Apache HTTP Server Path Traversal,7.2,3.0,True,0.918,78,20,2024-09-26 06:24:52 PM,2024-10-19 06:24:52 PM
CVE-2016-15454,Windows SMBv3 Remote Code Execution,6.19,9.8,True,0.081,37,7,2025-05-20 06:24:52 PM,2025-07-06 06:24:52 PM
CVE-2015-49402,OpenSSL Padding Oracle Vulnerability,5.18,7.2,True,0.808,67,1,2024-10-04 06:24:52 PM,2024-11-24 06:24:52 PM
CVE-2020-60752,Docker Privilege Escalation,6.97,7.9,False,0.726,88,5,2025-02-04 06:24:52 PM,2025-03-06 06:24:52 PM
CVE-2017-66993,Kubernetes API Misconfiguration,0.39,9.1,True,0.64,43,1,2025-05-07 06:24:52 PM,2025-05-15 06:24:52 PM
CVE-2022-15561,SQL Injection in Admin Panel,3.42,2.0,False,0.145,119,15,2025-04-22 06:24:52 PM,2025-05-25 06:24:52 PM
CVE-2023-50782,PHP CGI Argument Injection,8.34,6.2,False,0.014,37,23,2024-09-25 06:24:52 PM,2024-10-18 06:24:52 PM
CVE-2018-20475,Nginx Cache Poisoning,4.38,6.8,False,0.122,95,4,2024-08-27 06:24:52 PM,2024-10-09 06:24:52 PM
CVE-2015-33698,Linux Kernel LPE via OverlayFS,6.41,3.5,True,0.049,18,6,2025-02-12 06:24:52 PM,2025-03-17 06:24:52 PM
CVE-2022-73920,Java Spring Remote Code Execution,1.97,7.4,False,0.412,36,34,2024-08-04 06:24:52 PM,2024-09-23 06:24:52 PM
CVE-2016-64997,Log4j JNDI Injection,4.78,4.7,True,0.408,85,13,2025-05-11 06:24:52 PM,2025-07-09 06:24:52 PM
CVE-2020-98562,SolarWinds Orion API Exposure,9.38,6.9,False,0.508,12,5,2024-08-01 06:24:52 PM,2024-08-09 06:24:52 PM
CVE-2020-4390,Zimbra Auth Bypass,5.54,1.4,False,0.445,97,18,2024-12-19 06:24:52 PM,2025-02-01 06:24:52 PM
CVE-2015-90808,Chrome Use-After-Free,6.76,7.4,False,0.733,103,39,2024-12-30 06:24:52 PM,2025-02-26 06:24:52 PM
CVE-2022-6027,Mozilla Firefox Memory Corruption,1.98,8.5,False,0.548,76,20,2024-08-15 06:24:52 PM,2024-09-01 06:24:52 PM
CVE-2024-6461,Microsoft Exchange SSRF,4.75,0.1,True,0.311,43,17,2024-10-02 06:24:52 PM,2024-11-11 06:24:52 PM
CVE-2016-16832,Adobe Acrobat JS Engine Overflow,5.12,1.0,False,0.878,50,39,2025-07-11 06:24:52 PM,2025-07-27 06:24:52 PM
CVE-2024-87667,Fortinet SSL VPN Path Traversal,1.79,5.3,False,0.238,60,8,2024-11-24 06:24:52 PM,2025-01-18 06:24:52 PM
CVE-2023-68960,Cisco ASA DNS Rebinding,5.21,2.4,True,0.631,17,27,2024-10-30 06:24:52 PM,2024-11-20 06:24:52 PM
CVE-2020-22826,VMware ESXi Shell Injection,1.77,3.9,False,0.98,53,36,2025-06-05 06:24:52 PM,2025-06-16 06:24:52 PM
CVE-2023-29055,Citrix ADC Directory Traversal,2.0,3.7,True,0.497,9,31,2025-06-23 06:24:52 PM,2025-06-27 06:24:52 PM
CVE-2018-13103,F5 BIG-IP SSRF,9.03,3.9,False,0.674,1,37,2024-08-10 06:24:52 PM,2024-08-20 06:24:52 PM
CVE-2023-81025,Drupal Remote Code Execution,5.7,0.2,True,0.545,94,10,2025-04-19 06:24:52 PM,2025-06-03 06:24:52 PM
CVE-2021-76728,Jenkins Script Console Exposure,0.92,5.0,True,0.743,101,36,2025-02-19 06:24:52 PM,2025-03-15 06:24:52 PM
CVE-2022-4006,Jira XML External Entity Injection,7.15,7.7,False,0.496,50,6,2024-10-14 06:24:52 PM,2024-10-18 06:24:52 PM`
  }
]
